// Generated by CoffeeScript 1.6.3
'use strict';
var App;

App = angular.module('app', ['ngCookies', 'ngResource', 'ngRoute', 'app.controllers', 'app.directives', 'app.filters', 'app.services', 'partials']);

App.config([
  '$routeProvider', '$locationProvider', function($routeProvider, $locationProvider, config) {
    $routeProvider.when('/age', {
      templateUrl: '/partials/age.html',
      controller: 'ageCtrl'
    }).when('/home', {
      templateUrl: '/partials/home_login.html'
    }).when('/register', {
      templateUrl: '/partials/register.html',
      controller: 'registerCtrl'
    }).when('/congratulations', {
      templateUrl: '/partials/congratulations.html',
      controller: 'congratsCtrl'
    }).when('/connect', {
      templateUrl: '/partials/connect.html',
      controller: 'connectCtrl'
    }).when('/confirm_social', {
      templateUrl: '/partials/confirm_social.html',
      controller: 'confirm_socialCtrl'
    }).when('/profile', {
      templateUrl: '/partials/profile.html',
      controller: 'profileCtrl'
    }).when('/login', {
      templateUrl: '/partials/login.html',
      controller: 'loginCtrl'
    }).when('/prizes', {
      templateUrl: '/partials/prizes.html',
      controller: 'prizesCtrl'
    }).when('/verify_account', {
      templateUrl: '/partials/verify_account.html',
      controller: 'verifyaccountCtrl'
    }).when('/verify_email', {
      templateUrl: '/partials/verify_email.html',
      controller: 'verifyemailCtrl'
    }).when('/verify_sms', {
      templateUrl: '/partials/verify_sms.html',
      controller: 'verifysmsCtrl'
    }).when('/terms&conditions', {
      templateUrl: '/partials/terms.html',
      controller: 'termsCtrl'
    }).when('/my_profile', {
      templateUrl: '/partials/my_profile.html',
      controller: 'termsCtrl'
    }).when('/view2', {
      templateUrl: '/partials/partial2.html'
    }).otherwise({
      redirectTo: '/age'
    });
    return $locationProvider.html5Mode(false);
  }
]);
